

name: "Scorecard DepsDiffVis"
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    

jobs:
  Scorecard_DepsDiffVis:
    runs-on: ubuntu-latest
    steps:
      - name: Scorecard Dependency-Diff-in-PR Retrieval
        uses: actions/checkout@v3
        with:
          repository: aidenwang9867/DependencyDiffVisualizationInAction
          ref: v0
      - run: |
            results=$(./DependencyDiffVisualizationInAction \
            ${{github.actor}} \
            ${{github.event.repository.name}} \
            ${{secrets.GITHUB_TOKEN}} \
            c1e3869cc9ae93775549d5583994ba7f89761964 \
            65db129afcbb986e0e3ec4156333892a67594d76)
        
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hi there :wave:, here's the dependency changes on your code commit `${{github.event.pull_request.head.sha}}`
            ${{results}}
          pr_number: ${{github.event.pull_request.number}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
