name: Scorecards supply-chain security
on:
  pull_request:
    branches: [main]
jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Need the write permission to write to a pull request comment.
      pull-requests: write
      # Need the write permission to write annotations.
      checks: write
      actions: read
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: aidenwang9867/scorecard-action@depdiff_vis
        with:
          results_file: outputs.json
          results_format: json
          ## checks and change_types are for the dependency-diff Action
          checks: Maintained,Security-Policy,License,Code-Review,SAST
          change_types: added,removed
    env:
      GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
