

name: "Scorecard DepsDiffVis"
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    

jobs:
  Scorecard_DepsDiffVis:
    runs-on: ubuntu-latest
    steps:
      - name: Scorecard Dependency-Diff-in-PR Retrieval
        uses: actions/checkout@v3
      - run: |
            sudo \
            DependencyDiff \
            ${{github.actor}} \
            ${{github.event.repository.name}} \
            ${{secrets.GITHUB_TOKEN}} \
            ${{github.sha}} \
            ${{github.event.pull_request.head.sha}}
        
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hi there :wave:, here's the dependency changes on your code commit `${{github.event.pull_request.head.sha}}`
            123
          pr_number: ${{github.event.pull_request.number}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
