

name: "Scorecard DepsDiffVis"
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    

jobs:
  Scorecard_DepsDiffVis:
    name: Scorecard Dependency-Diff Visualization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            repository: aidenwang9867/DependencyDiffVisualizationInAction
            ref: v0
      - run: mkdir -p output/
      - run: |
            ./DependencyDiffVisualizationInAction \
            ossf \
            allstar \
            ${{secrets.GITHUB_TOKEN}} \
            c1e3869cc9ae93775549d5583994ba7f89761964 \
            65db129afcbb986e0e3ec4156333892a67594d76 \
            > output/results.md
      - uses: actions/upload-artifact@master
        with:
          name: results
          path: output
      - uses: actions/download-artifact@master
        with:
          name: results
      - name: comment on PR 1
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hi there :wave:, here's the dependency changes on your code commit `${{github.event.pull_request.head.sha}}`
          pr_number: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: comment PR 2
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/results.txt
