name: Scorecards supply-chain security
on:
  pull_request:
    branches: [main]
jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      # Need the write permission to write to a pull request comment.
      pull-requests: write
      actions: read
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: aidenwang9867/scorecard-action@main
        with:
          results_file: outputs.json
          results_format: json
          checks: License,Maintained
          change_types: added,updated
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
